version: '3'
services:

    nginx:
        container_name: nginx
        build: ./nginx
        image: popol/nginx:v1
        restart: always
        network_mode: "host"
        ports:
          - "80:80"
        volumes:
          - ./popol:/srv/popol
          - ./log:/var/log/nginx
          - ./popol/static/:/static
        depends_on:
          - django
    django:
        container_name: django
        build: ./popol
        image: popol/django:v1
        restart: always
        command: uwsgi --ini uwsgi.ini
        volumes:
          - ./popol:/srv/popol
          - ./log:/var/log/uwsgi
